config/routes.rb
Rails.application.routes.draw do

   root 'page#welcome'

   get 'photobook'=> 'page#photobook'
   post 'createphotobook' =>'photobooks#createphotobook'
   post 'photos/uploadphoto' =>'photos#uploadphoto'
   post 'photos/photolist' =>'photos#photolist'
   post 'photos/showphoto' =>'photos#showphoto'
   post 'photobooks/setbookcover'=>'photobooks#setbookcover'

   get 'signup' => 'users#signup' , :as =>'signup'
   get 'login'=> 'users#login', :as =>'login'
   post 'create_login_session' => 'users#create_login_session'
   get 'logout' =>'users#logout', :as =>'logout'
   post 'avatar/uploadavatar'=>'users#avatar'
   get ':username' =>'users#info'
   resources :users,only:[:create]
   resources  :mircoblogs,only:[:create]
   get 'mircoblog/:id' => 'mircoblogs#showformid' ,:as=>'showmircoblog'
   get 'mircoblogs/getMircoblogs.js' => 'mircoblogs#getmircoblogs'
   resources :comments
   post 'comments/photocomments' =>'comments#photocomments'
  get 'follow/user/:id' => 'follows#follow'

end

app/models/atuser.rb
class Atuser < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to:mircoblog
  belongs_to:photo
  belongs_to:user
  validates :comment, presence: true
end

app/models/follow.rb
class Follow < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/mircoblog.rb
class Mircoblog < ActiveRecord::Base
  belongs_to:user
  has_many:comments
  validates :sharetext, presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to:photobook
  has_many:comments
  mount_uploader :file, PhotoUploader
end

app/models/photobook.rb
class Photobook < ActiveRecord::Base
  has_many:photos
  validates :bookname ,presence: true
end

app/models/pointpraise.rb
class Pointpraise < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many:mircoblogs
  has_many:comments
  has_secure_password
  validates :username ,presence: true
  validates :username , uniqueness: { case_sensitive: false}
  mount_uploader :avatar, AvatarUploader
  #添加用户验证
  before_create { generate_token(:auth_token) }

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column =>self[column])
  end
end

app/models/user_dynamic.rb
class UserDynamic < ActiveRecord::Base
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def welcome
    #@mircoblogs= Mircoblog.all.reverse.take(10)

    #render :action=>"getMircoblogs"

  end

  def photobook
    @photobook = Photobook.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/mircoblogs_helper.rb
module MircoblogsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/photobook_helper.rb
module PhotobookHelper
end

app/helpers/photobooks_helper.rb
module PhotobooksHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>轻微博</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="<%= params[:controller] + '-' + params[:action] %>">
<%= render partial:'page/header' %>
<%= yield %>
<%= render partial:'page/footer' %>


</body>
</html>

app/views/page/_footer.html.erb
<div class="footer">
  <hr/>
  &copy; Make For Vsupa
</div>

app/views/page/_header.html.erb
<div class="topmenu navbar-fixed-top">
<div class="container ">
  <ul class="pull-right">
    <% if !current_user %>
        <li><a href="/login">登录</a></li>
        <li><a href="/signup">注册</a></li>
    <% else %>
        <li><%= link_to raw('<span class="glyphicon glyphicon-user"></span> '+current_user.username), current_user.username %></li>
        <!--<li> <a  href=""><span class="glyphicon glyphicon-envelope"><span class="msg_icon">199</span></span></a></li>-->
        <li><%= link_to raw('<span class="glyphicon glyphicon-off"></span>'+"登出"), logout_path %></li>

    <% end %>
  </ul>
</div>
</div>
<div class="jumbotron ccccc">
  <div class="container">
    <h1>云算盘-轻微博</h1>

    <div class="nav"><p>Nothing talk,Enjoy It!</p>
      <div class="navbtn">
        <ul>
          <li><%= link_to '微博', root_path %></li>
          <li><%= link_to '相册', photobook_path %></li>
        </ul>
      </div>
    </div>

    <p class="subtitle">分享您的快乐</p>
  </div>
</div>

app/views/page/photobook.html.erb
<%= render partial:'photobooks/photobooklist', locals: {photobook: @photobook} %>
<%if current_user&&current_user.id==1%>
<%= link_to "创建相册", "#", class: "btn btn-primary btn-sm", :data => {:toggle => "modal", :target => ".createphotobookModal"} %>
<%= link_to "上传照片", "#", class: "btn btn-primary btn-sm", :data => {:toggle => "modal", :target => ".uploadphotoModal"} %>
    <%= render partial: 'photos/uploadphotos' ,locals:{photobook: @photobook}%>
    <%= form_tag "/createphotobook" do %>
        <div class="modal fade createphotobookModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <a class="close" data-dismiss="modal" aria-hidden="true">x</a>
                <h4 class="modal-title">创建相册</h4>
              </div>
              <div class="modal-body">
                <div>相册名<%= text_field_tag :bookname, params[:bookname], :class => "", :style => "width:200px" %></div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal"> 关闭
                </button>
                <%= submit_tag "添加", :class => "submit-issue-button btn btn-primary" %></div>
            </div>
          </div>
        </div>
    <% end %>
<% end %>
    <%= render partial: 'photos/photos' %>
<script>

    $(function () {
        $('.showphotos').on("hide.bs.modal", function (e) {
            $('.photo').unbind();
            $(this).find(".modal-body").html("");

        });
        $(".uploadphotoModal").on("show.bs.modal", function () {

            createUploader();
        });

    });
    $(".showphoto").on("click", function () {
        var id = $(this).attr("data-photobookid");
        var show = $('.showphotos');
        $.ajax({
            url: "/photos/photolist",
            type: "post",
            data: {photobook_id: id},
            success: function (data) {
                var mbody = show.find(".modal-body");
                mbody.html(data);
                var img =  $(".p").children('img').attr("data-photoid");
                var imgs = $(".ppp img[data-photoid='"+img+"']");
                imgs.prev().addClass("active");
                bind();
            },
            dataType: 'html'
        });
        show.modal();

    });

    function createUploader() {
        var thumbnailuploader = new qq.FineUploader({
            element: document.getElementById('thumbnail-fine-uploader'),
            template: "qq-simple-thumbnails-template",
            request: {
                endpoint: '/photos/uploadphoto'
            },
            autoUpload: false,
            thumbnails: {
                placeholders: {
                    waitingPath: "/image/waiting-generic.png",
                    notAvailablePath: "/image/not_available-generic.png"
                }
            },
            validation: {
                allowedExtensions: ['jpeg', 'jpg', 'gif', 'png']
            },
            editFilename: {
                enabled: true
            }
        });
        $("#edit-file-upload-trigger").click(function () {
            thumbnailuploader.setParams({
                authenticity_token: "<%= form_authenticity_token.to_s %>",
                photobook_id: $("#photobookid").val()
            });
            thumbnailuploader.uploadStoredFiles();
        });
    }
</script>

app/views/page/welcome.html.erb
<div class="content">
  <div class="mircoblogs">
    <div class="talkbox">
      <h4>嘿，来给大家分享点快乐的事情吧</h4>
      <% if current_user%>
      <%= form_for Mircoblog.new(:user_id=>current_user.id) do |m| %>
      <%= m.text_area :sharetext ,:class => "hide" ,:id=>'sharetext'%>
              <div id="msgtxt" contenteditable="true" onblur="document.getElementById('sharetext').value=this.innerHTML"></div>
      <button type="submit" class="btn btn-success btn-sm pull-right">分享</button>
      <% end %>
          <% else%>
          <div id="msgtxt" contenteditable="true"></div>
          <button  class="btn btn-success btn-sm pull-right" data-toggle="modal" data-target=".loginmodal">分享</button>
          <% end %>
    </div>
    <div class="shardlist">
     <%= render partial:'mircoblogs/mircoblogslist',locals:{mircoblogs:Mircoblog.all.reverse.take(10)}%>
      <% if Mircoblog.all.count >10%>
      <div class="center"><a class="btn  btn-primary btn-lg showten" data-remote="true" href="mircoblogs/getMircoblogs.js?page=1" data-index="1">再显示10条</a></div>
          <% elsif Mircoblog.all.count <10 && Mircoblog.all.count > 0%>
          <div class="center"><a class="btn  btn-primary btn-lg showten" data-remote="true" href="mircoblogs/getMircoblogs.js?page=1" data-index="1">加载完成</a></div>
      <% else%>
          <div class="center"><a class="btn  btn-primary btn-lg showten" data-remote="true" href="mircoblogs/getMircoblogs.js?page=1" data-index="1">还没人分享</a></div>
      <% end %>
    </div>
  </div>
  <div class="side">
    <% if current_user%>
    <div class="userinfo">
      <div class="useravatar">
        <%= image_tag current_user.avatar_url(:large) || image_url("head.png")  if current_user.avatar  %>
      </div>

      <div class="username"><%= current_user.username%></div>
    </div>
        <%end%>
  </div>
</div>
<%= form_tag "/create_login_session" do %>
<div class="modal loginmodal fade">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <a class="close"  data-dismiss="modal" aria-hidden="true">x</a>
        <h4 class="modal-title">登陆</h4>
      </div>
      <div class="modal-body">
        <div class="input-group input-group-sm">
          <span class="input-group-addon" id="basic-addon1">用户名:</span>
          <%= text_field_tag :username, params[:username], :class => "form-control", :style => "" ,:placeholder=>"请输入用户名",:aria=>{describedby:"basic-addon1"}%>
        </div>
        <br/>
        <div class="input-group input-group-sm">
          <span class="input-group-addon" id="basic-addon1">密　码:</span>
          <%= password_field_tag :password, params[:password], :class => "form-control", :style => "" ,:placeholder=>"请输入密码",:aria=>{describedby:"basic-addon1"}%>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          关闭
        </button>
        <%= submit_tag "登陆", :class => "submit-issue-button btn btn-primary" %>
      </div>
    </div>
  </div>
</div>
<% end %>

<script>
  $(function(){
      var names = [{name:'neekin',id:'3'},{name:'kee',id:'4'}];
      var at_config = {
          at: "@",
          data: names,

          insertTpl:"<a href='${id}'>@${name}</a>",
          limit: 100
      };
      $("#msgtxt").atwho(at_config);
  });
</script>